name: Caller Workflow
on:
  push:
jobs:
  job1:
    outputs:
      job1_output: ${{ steps.outputid.outputs.testjoboutput }}
    runs-on: ubuntu-latest
    steps:
    - name: Add an env variable
      run: echo "testenv=helloworld" > $GITHUB_ENV

    - name: use env variable set in above step
      run: echo "${{ env.testenv }}"

    - name: add a variable to output
      id: outputid
      run: echo "testjoboutput=hellomario"> $GITHUB_OUTPUT

  job2:
    runs-on: ubuntu-latest
    steps:
    - name: print output from above job
      run: echo ${{ needs.job1.outputs.job1_output }}
      
  caller-job:
    uses: ./.github/workflows/reuse.yml
    with:
      input1: "test 123"
    
