name: Reusable workflow
on:
  workflow_call:
    inputs:
      input1:
        type: string
        required: true
    outputs:
      calledoutput:
        description: just a value sent from called workflow
        value: "this is a test"

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
    - name: echo output
      run: echo "${{ inputs.input1 }}"
